name: Waka Readme # Workflow 名稱

on:
  push:
    branches: 
      - main
  schedule:
    # Runs at 16:00 UTC ( at 24:00 Taiwan(UTC+8) )
    - cron: '0 16 * * *'
  # 允許你從 Action 頁簽上手動執行 workflow
  workflow_dispatch: 
jobs: 
  # # 可允許有多個job依循序/平行執行，使用 `jobs.<job_id>.needs`` 來設定每個 Job 相依性
  # job的名稱
  update-readme:
    name: Update Readme with Metrics
    # 這個 job 會執行在作業系統為 ubuntu 的 runner
    runs-on: ubuntu-latest
    # 以循序方式執行命令、設定工作與 action
    steps:
        # 可以使用已經定義好的 Action (放置於 workflow 相同的 Repo、public repo 或已經發布的 Docker Continer Registry) 來進行重複的工作
      # 
      # 選擇要執行的 Action，格式：{owner}/{repo}@{ref/branch}
      - uses: anmol098/waka-readme-stats@master
        with:
          # Parameters，帶入的參數、設定
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          COMMIT_MESSAGE : "Update README.md with Dev Metrics"
          SHOW_LINES_OF_CODE : True
          SHOW_DAYS_OF_WEEK : False
          SHOW_COMMIT : False
          SHOW_OS : False
          SHOW_TIMEZONE : False
          UPDATED_DATE_FORMAT: "%Y/%m/%d %H:%M"
          SYMBOL_VERSION : 1
          # See https://github.com/anmol098/waka-readme-stats for more info