name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          COMMIT_MESSAGE : "Update README.md with Dev Metrics"
          SHOW_LINES_OF_CODE : True
          SHOW_DAYS_OF_WEEK : False
          SHOW_COMMIT : False
          SHOW_OS : False
          SHOW_TIMEZONE : False
          SYMBOL_VERSION : 3