name: Waka Readme

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  schedule:
    # Runs at 12am(Taipei : UTC+10)
    - cron: "0 8 * * *"

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: bebeshen/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
